### ISSUE TITLE
Problème de `query params` pour la liste d'identifiants de services lors de l'export CSV

### ISSUE THREAD

**Issue by ThibaudMZN** [betagouv/mon-service-securise#1557]
Ce problème n'est pas simple à régler.
Il n'existe pas de version standard pour passer un tableau dans des `query params`.

La méthode qui semblait fonctionner avec notre stack serait :

##### Client
```js
let params = new URLSearchParams();
params.append('p', 'val1');
params.append('p', 'val2');
```

##### Serveur
```js
const { idsServices = [] } = requete.query;
if(!Array.isArray(idsServices)) throw new Error();
```

Le problème de cette approche est que `express` interprète un tableau de longueur 1 comme étant une string.

Lien vers le problème:
- [ ] https://github.com/betagouv/mon-service-securise/security/code-scanning/154

**Comment by CadiChris** [comment]
Idée jetée en l'air : si on reçoit une `string`, on la met dans un tableau, si on reçoit un tableau on l'utilise.

Dans les autres cas on jette une erreur directement depuis l'API.

**Comment by ThibaudMZN** [comment]
Corrigé avec #1560
